### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by born2net** [ColinEberhardt/angular2-todo#4]
```
 switch (action.type) {
    case 'ADD':
      return state.push(new TodoItem().setText(action.text));
      ...
```

I think you will be creating 2 instances of ToDos, one the new and one on the .setText Immutable return, no?

regards

Sean

**Comment by ColinEberhardt** [comment]
No, this is not a bug.

`ToDoItem` is immutable, the setters can be thought of a factory methods which create new instances with the given change in state.

Rather than create a constructor that allows you to supply an initial state, which would be a lot of extra effort, the constructor create a `TodoItem` with a default state. You can then create the require state via the 'setter' methods ...

```
new TodoItem().setText'hello').setCompletion(true);
```

Yes, the above code will create 3 `TodoItem` instances, however, the last one, with the required state, is returned.

This takes advantage of immutable.js which makes this kind of object manipulation quite efficient.

**Comment by born2net** [comment]
ok that's what I figured, that you are creating multiple Todo Items but only keeping the last, I guess to instantiate is cheap, so it's ok to create and not use the first two...

regards
